### ISSUE TITLE
Gro doesn't let you know when you have pending migrations

### ISSUE THREAD

**Issue by greatbacon** [feltcoop/gro#32]
When you pull a branch and there are unapplied migrations in it, gro doesn't bomb out of `gro dev` to let you know that still needs to be done, resulting in run time complications.

**Comment by ryanatkn** [comment]
Got the fix in [a PR here on the Felt repo](https://github.com/feltcoop/felt/pull/36). Right now Gro doesn't do anything db-related and Felt overrides the builtin `gro dev` task with its own fully custom version due to Sapper integration.

**Comment by greatbacon** [comment]
Ah, well I'll just go ahead and close this sucker out for now then!
